name: Grammar Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run grammar tests
      run: npm test

    - name: Generate test snapshots (on failure)
      if: failure()
      run: npm run test:snap
      continue-on-error: true
